export const documentConstants = {
  GET_DOCUMENT_REQUEST: 'DOCUMENTS_GET_REQUEST',
  GET_DOCUMENT_SUCCESS: 'DOCUMENTS_GET_SUCCESS',
  GET_DOCUMENT_FAILURE: 'DOCUMENT_GET_FAILURE',

  EDIT_DOCUMENT_REQUEST: 'DOCUMENT_EDIT_REQUEST',

  CREATE_DOCUMENT_REQUEST: 'DOCUMENT_CREATE_REQUEST',
  CREATE_DOCUMENT_SUCCESS: 'DOCUMENT_CREATE_SUCCESS',

  SAVE_DOCUMENT_REQUEST: 'DOCUMENTS_SAVE_REQUEST',

  CLEAR_DOCUMENT: 'DOCUMENTS_CLEAR',
};