export const documentConstants = {
  GET_DOCUMENT_REQUEST: 'DOCUMENTS_GET_REQUEST',
  GET_DOCUMENT_SUCCESS: 'DOCUMENTS_GET_SUCCESS',
  GET_DOCUMENT_FAILURE: 'DOCUMENT_GET_FAILURE',

  EDIT_DOCUMENT_REQUEST: 'DOCUMENT_EDIT_REQUEST',

  CREATE_DOCUMENT_REQUEST: 'DOCUMENT_CREATE_REQUEST',
  CREATE_DOCUMENT_CANCEL: 'DOCUMENT_CREATE_CANCEL',
  CREATE_DOCUMENT_SUCCESS: 'DOCUMENT_CREATE_SUCCESS',

  SAVE_DOCUMENT_REQUEST: 'DOCUMENTS_SAVE_REQUEST',

  SHARE_DOCUMENT_REQUEST: 'DOCUMENT_SHARE_REQUEST',
  SHARE_DOCUMENT_SUCCESS: 'DOCUMENT_SHARE_SUCCESS',
  SHARE_DOCUMENT_CANCEL: 'DOCUMENT_SHARE_CANCEL',

  DELETE_DOCUMENT_REQUEST: 'DOCUMENT_DELETE_REQUEST',
  DELETE_DOCUMENT_SUCCESS: 'DOCUMENT_DELETE_SUCCESS',
  DELETE_DOCUMENT_FAILURE: 'DOCUMENT_DELETE_FAILURE',

  CLEAR_DOCUMENT: 'DOCUMENTS_CLEAR',
};