# Generated by Django 2.0.2 on 2018-04-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharemarkdown', '0006_update_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='name',
            new_name='folder_name',
        ),
    ]
