# Generated by Django 2.0.4 on 2018-04-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharemarkdown', '0007_update_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(default='', null=True),
        ),
    ]
